version: '3.8'

services:
  mysql1:
    image: mysql:5.7
    container_name: mysql1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - mysql1_data:/var/lib/mysql

  mysql2:
    image: mysql:5.7
    container_name: mysql2
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - mysql2_data:/var/lib/mysql

  mysql3:
    image: mysql:5.7
    container_name: mysql3
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3308:3306"
    volumes:
      - mysql3_data:/var/lib/mysql

volumes:
  mysql1_data:
  mysql2_data:
  mysql3_data:
