version: '3'

services:
  mysql-common:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: business_db
    volumes:
      - mysql_business_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mysql-quartz:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quartz_db
    volumes:
      - mysql_quartz_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app1:
    build: .
    depends_on:
      - mysql-common
      - mysql-quartz
    environment:
      COMMON_DATASOURCE_URL: jdbc:mysql://mysql-common:3306/business_db?useSSL=false
      COMMON_DATASOURCE_USERNAME: root
      COMMON_DATASOURCE_PASSWORD: rootpassword
      QUARTZ_DATASOURCE_URL: jdbc:mysql://mysql-quartz:3306/quartz_db?useSSL=false
      QUARTZ_DATASOURCE_USERNAME: root
      QUARTZ_DATASOURCE_PASSWORD: rootpassword
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  app2:
    build: .
    depends_on:
      - mysql-common
      - mysql-quartz
    environment:
      COMMON_DATASOURCE_URL: jdbc:mysql://mysql-common:3306/business_db?useSSL=false
      COMMON_DATASOURCE_USERNAME: root
      COMMON_DATASOURCE_PASSWORD: rootpassword
      QUARTZ_DATASOURCE_URL: jdbc:mysql://mysql-quartz:3306/quartz_db?useSSL=false
      QUARTZ_DATASOURCE_USERNAME: root
      QUARTZ_DATASOURCE_PASSWORD: rootpassword
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

volumes:
  mysql_business_data:
  mysql_quartz_data: